services:
  bank_simulator:
    container_name: bank_simulator
    image: bbyars/mountebank:2.8.1
    ports:
      - "2525:2525"
      - "8080:8080"
    command: --configfile /imposters/bank_simulator.ejs --allowInjection
    volumes:
      - type: bind
        source: ./imposters
        target: /imposters


  postgres:
    container_name: payments_db
    image: postgres:18.1-alpine
    environment:
      POSTGRES_DB: payments_db
      POSTGRES_USER: payments_user
      POSTGRES_PASSWORD: payments_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U payments_user -d payments_db" ]
      interval: 5s
      timeout: 5s
      retries: 10


volumes:
  pgdata:
    driver: local